# Generated by Django 5.1.4 on 2025-01-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advising_class', to=settings.AUTH_USER_MODEL),
        ),
    ]
