# Generated by Django 5.1.4 on 2025-01-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_created_at_classroom_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_on',
        ),
    ]
