# Generated by Django 5.1.4 on 2025-01-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_classroom_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('drive_id', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('pptx', 'Powerpoint Presentation'), ('xlsx', 'Excel Spreadsheet'), ('jpg', 'JPEG Image'), ('png', 'PNG Image'), ('mp4', 'MP4 Video'), ('other', 'Other File Type')], max_length=20)),
                ('mime_type', models.CharField(choices=[('application/pdf', 'PDF Document'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'Word Document'), ('application/vnd.openxmlformats-officedocument.presentationml.presentation', 'PowerPoint Presentation'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Excel Spreadsheet'), ('image/jpeg', 'JPEG Image'), ('image/png', 'PNG Image'), ('video/mp4', 'MP4 Video')], max_length=255, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
