# Generated by Django 5.1.4 on 2025-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='drive_web_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
