# Generated by Django 5.1.4 on 2025-01-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_file_file_size_alter_course_classroom_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_imgs/'),
        ),
    ]
