# Generated by Django 5.1.4 on 2025-01-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='drive_folder',
        ),
        migrations.AddField(
            model_name='classroom',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='classroom',
            name='spreadsheet_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
