# Generated by Django 5.1.4 on 2025-01-20 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_spreadsheet_id_classroom_sheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.classroom'),
        ),
    ]
