# Generated by Django 5.1.4 on 2025-02-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_folder_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
