# Generated by Django 5.1.4 on 2025-02-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_classroom_classroom_folder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='drive_folder_id',
            new_name='grade_folder_id',
        ),
    ]
