# Generated by Django 5.1.4 on 2025-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_drive_folder_id_classroom_grade_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_folder_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
