# Generated by Django 5.1.4 on 2025-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_course_course_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contents_count',
            field=models.IntegerField(default=0),
        ),
    ]
