# Generated by Django 5.1.4 on 2025-02-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_course_contents_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contents_count',
        ),
    ]
