# Generated by Django 5.1.4 on 2025-02-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_course_contents_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='grade',
            new_name='grade_level',
        ),
    ]
