# Generated by Django 5.1.4 on 2025-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_grade_classroom_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_catgeory',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('course', 'Course Material'), ('classrom', 'Classroom Material'), ('school', 'School Material'), ('other', 'Other Material')], default='other', max_length=20),
        ),
    ]
