# Generated by Django 5.1.4 on 2025-02-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_content_content_catgeory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_catgeory',
        ),
        migrations.AddField(
            model_name='content',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('course', 'Course Material'), ('classroom', 'Classroom Material'), ('school', 'School Material')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.classroom'),
        ),
        migrations.AlterField(
            model_name='content',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.course'),
        ),
        migrations.AlterField(
            model_name='content',
            name='visibility',
            field=models.CharField(choices=[('school', 'School'), ('classroom', 'Classroom'), ('course', 'Course')], default='classroom', max_length=20),
        ),
    ]
