# Generated by Django 5.1.4 on 2025-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_content_content_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='grade_level',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
