# Generated by Django 5.1.4 on 2025-03-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_content_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentattachment',
            name='attachment_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='contentattachment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentattachment',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='api.file'),
        ),
    ]
