# Generated by Django 5.1.4 on 2025-03-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_contentattachment_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentattachment',
            name='attachment_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL')], default='file', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentattachment',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.file'),
        ),
    ]
