# Generated by Django 5.1.4 on 2025-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_contentattachment_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('attached', 'Attached'), ('mixed', 'Mixed')], default='text', max_length=20),
        ),
    ]
