# Generated by Django 5.1.4 on 2025-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='senior_high',
            field=models.BooleanField(default=True),
        ),
    ]
